ALARM_CODE = {
        '10':'Anti_theft Alarm',
        '11':'Analog 1 voltage increase' ,
        '12':'Analog 1 voltage decrease' ,
        '13':'Analog 2 voltage increase' ,
        '14':'Analog 2 voltage decrease' ,
        '15':'ACC on' ,
        '16':'ACC off' ,
        '17':'AC on' ,
        '18':'AC off' ,
        '19':'Idle start' ,
        '1' :'External power disconnect' ,
        '20':'Idle end', 
        '21':'GSM jammer detection start',
        '22':'GSM jammer detection end',
        '23':'External power recover',
        '24':'External power lower',
        '25':'digital 3 input from 0 to 1',
        '26':'digital 3 input from 1 to 0',
        '27':'digital 4 input from 0 to 1',
        '28':'digital 4 input from 1 to 0',
        '29':'digital 5 input from 1 to 0',
        '2' :'Inner power lower',
        '30':'digital 5 input from 0 to 1', 
        '31':'digital 6 input from 1 to 0',
        '32':'digital 6 input from 0 to 1',
        '33':'Analog 3 voltage increase',
        '34':'Analog 3 voltage decrease',
        '35':'Analog 4 voltage increase',
        '36':'Analog 4 voltage decrease',
        '37':'Analog 4 voltage decrease',
        '3':'SOS',
        '4':'Over speed',
        '5':'In geofence',
        '6':'out geofence',
        '7':'Drag alarm',
        '8':'Vibration alarm',
        '9': 'Device apply address',
}